### ISSUE TITLE
AssertionError: Override list has odd length: ['\\']; it must be a list of pairs

### ISSUE THREAD

**Issue by qdvan3546** [HRNet/HRNet-Human-Pose-Estimation#19]
My error, I train on google colab:

/content/drive/MyDrive/Colab Notebooks/HR pose/HRNet-Human-Pose-Estimation
Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab Notebooks/HR pose/HRNet-Human-Pose-Estimation/tools/train.py", line 223, in <module>
    main()
  File "/content/drive/MyDrive/Colab Notebooks/HR pose/HRNet-Human-Pose-Estimation/tools/train.py", line 78, in main
    update_config(cfg, args)
  File "/content/drive/MyDrive/Colab Notebooks/HR pose/HRNet-Human-Pose-Estimation/tools/../lib/config/default.py", line 129, in update_config
    cfg.merge_from_list(args.opts)
  File "/usr/local/lib/python3.10/dist-packages/yacs/config.py", line 223, in merge_from_list
    _assert_with_logging(
  File "/usr/local/lib/python3.10/dist-packages/yacs/config.py", line 545, in _assert_with_logging
    assert cond, msg
AssertionError: Override list has odd length: ['\\']; it must be a list of pairs

**Comment by qdvan3546** [comment]
If you get this error, it's just basic syntax on google colab:
+ Syntax:
python tools/train.py\
     --cfg experiments/coco/hrnet/w32_256x192_adam_lr1e-3.yaml \
+I convert it to:
!python tools/train.py --cfg experiments/coco/hrnet/w32_256x192_adam_lr1e-3.yaml
